import Head from "next/head";
import { Inter } from "next/font/google";
import { useEffect, useState } from "react";
import { Data } from "@/getters";
import { TestStatusTable, TestStatusItem } from "@/app";
import axios from "axios";
import { ReleaseStatusTable } from "@/app/ReleaseStatusTable";
import Layout from "@/app/layout";
import { PageSection, Tab, Tabs, TabTitleText } from "@patternfly/react-core";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [repoStatuses, setRepoStatuses] = useState<Data>({
    repos: [],
    statuses: {},
  });

  const refresh = () =>
    axios.get("/api/status").then((res) => setRepoStatuses(res.data));

  useEffect(() => {
    refresh();
  }, []);

  const syncRepos = async () => {
    const promises = repoStatuses.repos
      .filter((repo) => repoStatuses.statuses[repo].syncStatus !== "synced")
      .map((repo) =>
        axios.post("/api/sync", null, { params: { repo, branch: "main" } })
      );
    await Promise.all(promises);
    await refresh();
  };

  const renewBumps = async () => {
    const promises = repoStatuses.repos.map((repo) =>
      axios.post("/api/close", null, { params: { repo } })
    );
    await Promise.all(promises);
    await refresh();
  };

  const statusItems: TestStatusItem[] = repoStatuses.repos.map((repoName) => {
    const { workflowStatus, ...data } = repoStatuses.statuses[repoName];

    return { name: repoName, status: workflowStatus, ...data };
  });

  const [activeTabKey, setActiveTabKey] = useState<string | number>(0);

  return (
    <>
      <Head>
        <title>PatternFly status dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Favicon-Light.png" />
      </Head>
      <Layout>
        <PageSection type="tabs">
          <Tabs activeKey={activeTabKey} onSelect={(_evt, key) => setActiveTabKey(key)}>
            <Tab eventKey={0} title={<TabTitleText>Test Status</TabTitleText>}>
              <TestStatusTable
                statusItems={statusItems}
                refresh={refresh}
                submit={syncRepos}
                renewBumps={renewBumps}
              />
            </Tab>
            <Tab eventKey={1} title={<TabTitleText>Release Status</TabTitleText>}>
              <ReleaseStatusTable />
            </Tab>
          </Tabs>
        </PageSection>
      </Layout>
    </>
  );
}
