import Head from "next/head";
import { Inter } from "next/font/google";
import { useEffect, useState } from "react";
import { getStatus, Data } from "@/getters";
import { Layout, StatusTable, StatusItem } from "@/app";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [repoStatuses, setRepoStatuses] = useState<Data>({
    repos: [],
    statuses: {},
  });
  const [selectedItems, setSelectedItems] = useState<string[]>([]);

  const refresh = () => getStatus().then((res) => setRepoStatuses(res));
  useEffect(() => {
    refresh();
  }, []);

  const submit = () => {};

  const statusItems: StatusItem[] = repoStatuses.repos.map((repoName) => ({
    name: repoName,
    status: repoStatuses.statuses[repoName],
  }));

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <StatusTable
          statusItems={statusItems}
          selectedItems={selectedItems}
          setSelectedItems={setSelectedItems}
          refresh={refresh}
          submit={submit}
        />
      </Layout>
    </>
  );
}
